### PR TITLE
fix numeric limits for char data type on power9

### PR DESCRIPTION
**Pull request by jglaser**
Compiling CUB headers with jitify/NVRTC on Power9 (Summit) with cuda 10.1.243, I get the following compilation error:

```
limits(33): error: invalid narrowing conversion from "int" to "char": constant value does not fit in destination type

limits(33): warning: integer conversion resulted in a change of sign
```

This PR fixes the compiler error, albeit it requires C++11. Maybe there is a C99 workaround, too?

### CODE REVIEW

**Comment by maddyscientist** [comment]
Thanks @jglaser.  I'm fine with this fix requiring C++11, but it should be wrapped with `#if __cplusplus >= 201103L` so this doesn't break older versions.

**Comment by benbarsdell** [comment]
Indeed thanks for this! The fix should probably be here instead though:
https://github.com/NVIDIA/jitify/blob/68e75143cdb07a322eb3aa87c2648bd02209f44f/jitify.hpp#L1423-L1429

We should replace the use of `#ifdef __CHAR_UNSIGNED__` with something like what's in your commit, and then numeric_limits will work as-is.

Also you can just use an enum to avoid requiring c++11 I think.

**Comment by jglaser** [comment]
Thanks for the tip with `enum`, @benbarsdell . I made this change and can confirm it is still working. I think the problem with fixing the (lack of) the original preprocessor define, `__CHAR_UNSIGNED__`  on the level of an `#include` is harder, since `(char)` casts at the  preprocessor stage are not supposed to work in order to conditionally define a macro, but I haven't tried. I am assuming this issue would need to be fixed in the NVRTC library itself.

**Comment by benbarsdell** [comment]
We could replace the CHAR_MIN/MAX macros with enums like this:
```
enum {
  _JITIFY_CHAR_IS_UNSIGNED = (char)-1 >= 0,
  CHAR_MIN = _JITIFY_CHAR_IS_UNSIGNED ? 0 : SCHAR_MIN,
  CHAR_MAX = _JITIFY_CHAR_IS_UNSIGNED ? UCHAR_MAX : SCHAR_MAX,
};
```

**Comment by jglaser** [comment]
yup. that works.

**Comment by maddyscientist** [comment]
Thanks @jglaser for iterating with us and for this fix.  Merging now.

**Pull request merged**
